# Pipeline for building artifacts for tagged versions leveraging the 
# GitVersion task

# TODO: Adjust the trigger to be just what we want
#trigger:

# Work around the default PR trigger on everything... :facepalm:
pr: 
  branches: 
    exclude:
    - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Use the BuildVersioning task!
- task: GitVersion@5
  inputs:
    runtime: 'core'

- task: Assembly-Info-NetCore@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: '**/*Hello.csproj'
    InsertAttributes: true
    GeneratePackageOnBuild: true
    VersionNumber: '$(GitVersion.AssemblySemVer)'
    FileVersionNumber: '$(GitVersion.AssemblySemFileVer)'
    InformationalVersion: '$(GitVersion.InformationalVersion)'
    PackageVersion: '$(GitVersion.FullSemVer)'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Test solution'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# DocFx building
- task: DocFxTask@0
  inputs:
    solution: 'docfx_project/docfx.json'
#  condition: and(succeeded(), )

- task: CopyFiles@2
  displayName: 'Copy nupkg(s) to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: CopyFiles@2
  displayName: 'Copy DocFx output to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**\docfx_project\_site\**'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
